package com.zenith.generator;

import com.palantir.javapoet.*;
import com.zenith.DataGenerator;
import com.zenith.mc.block.BlockStatePropertyDefinition;
import com.zenith.mc.block.properties.BlockStateProperties;
import com.zenith.mc.block.properties.api.Property;
import it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import net.minecraft.core.registries.BuiltInRegistries;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

public class BlockstatePropertiesGenerator implements Generator {
    @Override
    public void generate() {
        final String className = "BlockStatePropertyRegistry";
        final String packageName = "com.zenith.mc.block";
        Int2ObjectMap<Map<String, String>> blockIdToProperties = new Int2ObjectLinkedOpenHashMap<>();

        var blockRegistry = BuiltInRegistries.BLOCK;
        blockRegistry.forEach(block -> {
            int id = blockRegistry.getId(block);
            var defaultState = block.defaultBlockState();

            Map<String, String> propertyFieldNameToDefaultValue = new LinkedHashMap<>();
            for (var prop : block.getStateDefinition().getProperties()) {
                String value = defaultState.getValue(prop).toString();
                String fieldName = toStaticPropertyFieldName(prop);
                if (getZenithProperty(fieldName) == null) {
                    throw new RuntimeException("Missing ZenithProxy property field: " + fieldName + " for property: " + prop.getName());
                }
                propertyFieldNameToDefaultValue.put(fieldName, value);
            }
            blockIdToProperties.put(id, propertyFieldNameToDefaultValue);
        });

        ParameterizedTypeName mapFieldType = ParameterizedTypeName.get(Int2ObjectMap.class, BlockStatePropertyDefinition.class);
        var mapFieldSpec = FieldSpec.builder(mapFieldType, "STATES")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .initializer("new $T<>()", Int2ObjectOpenHashMap.class)
            .build();

        int count = 0;
        var mapInitializerBlock = CodeBlock.builder();
        for (var entry : blockIdToProperties.int2ObjectEntrySet()) {
            int blockId = entry.getIntKey();
            Map<String, String> properties = entry.getValue();
            if (properties.isEmpty()) continue;
            var statementBuilder = CodeBlock.builder()
                .add("$N.put($L, new $T(", mapFieldSpec, blockId, BlockStatePropertyDefinition.class);
            for (var iterator = properties.entrySet().iterator(); iterator.hasNext(); ) {
                final var propEntry = iterator.next();
                String fieldName = propEntry.getKey();
                String value = propEntry.getValue();
                statementBuilder.add("$L, $S", fieldName, value);
                if (iterator.hasNext()) {
                    statementBuilder.add(", ");
                }
            }
            statementBuilder.add("))");
            mapInitializerBlock.addStatement(statementBuilder.build());
            count++;
        }

        var typeSpec = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(mapFieldSpec)
            .addStaticBlock(mapInitializerBlock.build())
            .build();
        String[] propertyFieldNames = Arrays.stream(BlockStateProperties.class.getFields()).map(Field::getName).toList().toArray(String[]::new);
        var javaFile = JavaFile
            .builder(packageName, typeSpec)
            .addStaticImport(BlockStateProperties.class, "*")
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        DataGenerator.LOG.info("{} generated with {} instances!", className, count);
    }

    private String toStaticPropertyFieldName(final net.minecraft.world.level.block.state.properties.Property<?> property) {
        try {
            for (var mcField : net.minecraft.world.level.block.state.properties.BlockStateProperties.class.getFields()) {
                if (property == mcField.get(null)) {
                    return mcField.getName();
                }
            }
            throw new RuntimeException("No matching static field found for property: " + property.getName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private Property getZenithProperty(String fieldName) {
        try {
            return (Property) BlockStateProperties.class.getField(fieldName).get(null);
        } catch (Exception e) {
            throw new RuntimeException("No matching Zenith property found for field: " + fieldName, e);
        }
    }
}
