package com.zenith.generator;

import com.palantir.javapoet.*;
import com.zenith.DataGenerator;
import com.zenith.mc.DynamicRegistry;
import com.zenith.mc.RegistryData;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;
import java.util.function.Supplier;

public abstract class DynamicRegistryGenerator<T extends RegistryData> implements Generator {
    protected final Class<T> dataType;
    protected final String classPackage;
    protected final String registryClassName;

    public DynamicRegistryGenerator(
        Class<T> dataType,
        String classPackage,
        String registryClassName
    ) {
        this.dataType = dataType;
        this.classPackage = classPackage;
        this.registryClassName = registryClassName;
    }

    public abstract List<T> buildDataList();
    public abstract CodeBlock dataInitializer(T data);

    @Override
    public void generate() {
        List<T> dataList = buildDataList();

        ParameterizedTypeName registryType = ParameterizedTypeName.get(DynamicRegistry.class, dataType);
        var registryField = FieldSpec
            .builder(registryType, "REGISTRY")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .initializer("new $T(" + dataList.size() + ")", registryType)
            .build();

        var dataSupplierFields = dataList.stream()
            .map(dataInstance -> FieldSpec.builder(ParameterizedTypeName.get(Supplier.class, dataType), dataInstance.name().toUpperCase())
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer(CodeBlock.builder()
                    .add("() -> $N.get($S)", registryField, dataInstance.name())
                    .build())
                .build())
            .toList();

         var staticInitializerBlock = CodeBlock.join(
             dataList.stream()
                 .map(dataInstance -> CodeBlock.builder()
                     .addStatement("$N.register($L)", registryField, dataInitializer(dataInstance))
                     .build())
                 .toList(),
             ""
         );

        var typeSpec = TypeSpec.classBuilder(registryClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(registryField)
            .addFields(dataSupplierFields)
            .addStaticBlock(staticInitializerBlock)
            .build();
        var javaFile = JavaFile
            .builder(classPackage, typeSpec)
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        DataGenerator.LOG.info("{} generated with {} instances!", registryClassName, dataList.size());
    }

}
