package com.zenith.generator;

import com.palantir.javapoet.*;
import com.zenith.DataGenerator;
import com.zenith.mc.JsonRegistrySpec;
import com.zenith.mc.Registry;
import com.zenith.mc.RegistryData;

import javax.lang.model.element.Modifier;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.List;

import static com.zenith.DataGenerator.LOG;

public abstract class JsonRegistryGenerator<T extends RegistryData> implements Generator {
    protected final Class<T> dataType;
    protected final String classPackage;
    protected final String registryClassName;
    protected final Class<? extends JsonRegistrySpec<T>> registrySpecClass;
    protected final String jsonFileName;

    public JsonRegistryGenerator(
        final Class<T> dataType,
        final String registryClassName,
        final Class<? extends JsonRegistrySpec<T>> registrySpecClass,
        final String jsonFileName
    ) {
        this.dataType = dataType;
        this.classPackage = dataType.getPackage().getName();
        this.registryClassName = registryClassName;
        this.registrySpecClass = registrySpecClass;
        this.jsonFileName = jsonFileName;
    }

    public abstract List<T> buildDataList();

    public void dumpJson(List<T> dataList) {
        try (Writer out = new FileWriter(DataGenerator.outputFile(jsonFileName))) {
            DataGenerator.gson.toJson(dataList, out);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        LOG.info("Dumped {}", jsonFileName);
    }

    @Override
    public void generate() {
        List<T> dataList = buildDataList();

        dumpJson(dataList);

        ParameterizedTypeName registryType = ParameterizedTypeName.get(Registry.class, dataType);
        var registryField = FieldSpec
            .builder(registryType, "REGISTRY")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .initializer("new $T(" + dataList.size() + ")", registryType)
            .build();

        var dataInstanceFields = dataList.stream()
            .map(dataInstance -> FieldSpec.builder(dataType, dataInstance.name().toUpperCase())
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .build())
            .toList();

        var staticInitBlockBuilder = CodeBlock.builder();
        staticInitBlockBuilder.addStatement("var jsonRegistrySpec = new $T()", registrySpecClass);
        staticInitBlockBuilder.addStatement("var data = jsonRegistrySpec.read()");
        for (T dataInstance : dataList) {
            staticInitBlockBuilder.addStatement("$N = REGISTRY.register(data.get($L))",
                dataInstance.name().toUpperCase(),
                dataInstance.id()
            );
        }

        var typeSpec = TypeSpec.classBuilder(registryClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(registryField)
            .addFields(dataInstanceFields)
            .addStaticBlock(staticInitBlockBuilder.build())
            .build();
        var javaFile = JavaFile
            .builder(classPackage, typeSpec)
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        LOG.info("{} generated with {} instances!", registryClassName, dataList.size());
    }
}
