package com.zenith.generator.impl;

import com.palantir.javapoet.*;
import com.zenith.DataGenerator;
import com.zenith.generator.Generator;
import com.zenith.mc.block.BlockStatePropertyDefinition;
import com.zenith.mc.block.properties.api.BlockStateProperties;
import com.zenith.mc.block.properties.api.Property;
import it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import net.minecraft.core.registries.BuiltInRegistries;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class BlockstatePropertiesGenerator implements Generator {
    @Override
    public void generate() {
        final String className = "BlockStatePropertyRegistry";
        final String packageName = "com.zenith.mc.block";
        Int2ObjectMap<List<String>> blockIdToProperties = new Int2ObjectLinkedOpenHashMap<>();

        var blockRegistry = BuiltInRegistries.BLOCK;
        blockRegistry.forEach(block -> {
            int id = blockRegistry.getId(block);
            List<String> propertyFieldNames = new ArrayList<>();
            for (var prop : block.getStateDefinition().getProperties()) {
                String fieldName = toStaticPropertyFieldName(prop);
                if (getZenithProperty(fieldName) == null) {
                    throw new RuntimeException("Missing ZenithProxy property field: " + fieldName + " for property: " + prop.getName());
                }
                propertyFieldNames.add(fieldName);
            }
            blockIdToProperties.put(id, propertyFieldNames);
        });

        ParameterizedTypeName mapFieldType = ParameterizedTypeName.get(Int2ObjectMap.class, BlockStatePropertyDefinition.class);
        var mapFieldSpec = FieldSpec.builder(mapFieldType, "STATES")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .initializer("new $T<>($L)", Int2ObjectOpenHashMap.class, (int) blockRegistry.stream().count())
            .build();

        int count = 0;
        var mapInitializerBlock = CodeBlock.builder();
        for (var entry : blockIdToProperties.int2ObjectEntrySet()) {
            int blockId = entry.getIntKey();
            List<String> propertyFieldNames = entry.getValue();
            if (propertyFieldNames.isEmpty()) continue;
            var statementBuilder = CodeBlock.builder()
                .add("$N.put($L, new $T(", mapFieldSpec, blockId, BlockStatePropertyDefinition.class);
            for (var iterator = propertyFieldNames.iterator(); iterator.hasNext(); ) {
                final var fieldName = iterator.next();
                statementBuilder.add("$L", fieldName);
                if (iterator.hasNext()) {
                    statementBuilder.add(", ");
                }
            }
            statementBuilder.add("))");
            mapInitializerBlock.addStatement(statementBuilder.build());
            count++;
        }

        var typeSpec = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(mapFieldSpec)
            .addStaticBlock(mapInitializerBlock.build())
            .build();
        var javaFile = JavaFile
            .builder(packageName, typeSpec)
            .addStaticImport(BlockStateProperties.class, "*")
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        DataGenerator.LOG.info("{} generated with {} instances!", className, count);
    }

    private String toStaticPropertyFieldName(final net.minecraft.world.level.block.state.properties.Property<?> property) {
        try {
            for (var mcField : net.minecraft.world.level.block.state.properties.BlockStateProperties.class.getFields()) {
                if (property == mcField.get(null)) {
                    return mcField.getName();
                }
            }
            throw new RuntimeException("No matching static field found for property: " + property.getName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private Property getZenithProperty(String fieldName) {
        try {
            return (Property) BlockStateProperties.class.getField(fieldName).get(null);
        } catch (Exception e) {
            throw new RuntimeException("No matching Zenith property found for field: " + fieldName, e);
        }
    }
}
