package com.zenith.generator.impl;

import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import com.zenith.DataGenerator;
import com.zenith.generator.Generator;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.Arrays;

public class ItemTagsGenerator implements Generator {
    @Override
    public void generate() {
        var enumBuilder = TypeSpec.enumBuilder("ItemTags")
            .addModifiers(Modifier.PUBLIC);

        var tags = Arrays.stream(ItemTags.class.getDeclaredFields())
            .filter(field -> field.getType().equals(TagKey.class))
            .map(Field::getName)
            .toList();
        tags.forEach(enumBuilder::addEnumConstant);

        var enumTypeSpec = enumBuilder.build();
        var javaFile = JavaFile
            .builder("com.zenith.mc.item", enumTypeSpec)
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        DataGenerator.LOG.info("{} generated with {} instances!", "ItemTags", tags.size());
    }
}
