name: Run DataGenerator

on:
  pull_request:
  push:
    branches:
      - "1.21.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - name: Run Data Generator
        run: ./gradlew runServer

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: data
          path: build/data/

